//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeizi.Curso.RH.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeizi.Curso.RH.Domain.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de inicio do contrato deve ser informada..
        /// </summary>
        public static string DataContratoObrigatoria {
            get {
                return ResourceManager.GetString("DataContratoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data de inicio..
        /// </summary>
        public static string DatadeInicioNaoInformada {
            get {
                return ResourceManager.GetString("DatadeInicioNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dias de férias..
        /// </summary>
        public static string DiasDeFeriasNaoInformada {
            get {
                return ResourceManager.GetString("DiasDeFeriasNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível gozar férias antes de 1 ano de contrato..
        /// </summary>
        public static string FeriasAposAnoContrato {
            get {
                return ResourceManager.GetString("FeriasAposAnoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o id do contrato..
        /// </summary>
        public static string IDContratoNaoInformado {
            get {
                return ResourceManager.GetString("IDContratoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dias de abono não pode ser superior a {0}..
        /// </summary>
        public static string MaximoDiasDeAbono {
            get {
                return ResourceManager.GetString("MaximoDiasDeAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dias de férias não pode ser superior a {0} dias..
        /// </summary>
        public static string MaximoDiasDeFerias {
            get {
                return ResourceManager.GetString("MaximoDiasDeFerias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome do colaborador..
        /// </summary>
        public static string NomeColaborador {
            get {
                return ResourceManager.GetString("NomeColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação contratual deve ter no máximo 100 caracteres..
        /// </summary>
        public static string ObservacaoContratual {
            get {
                return ResourceManager.GetString("ObservacaoContratual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o periodo aquisitivo..
        /// </summary>
        public static string PeriodoAquisitivoNaoInformado {
            get {
                return ResourceManager.GetString("PeriodoAquisitivoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o salário contratual..
        /// </summary>
        public static string SalarioContratual {
            get {
                return ResourceManager.GetString("SalarioContratual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe saldo de férias..
        /// </summary>
        public static string SaldoDeFerias {
            get {
                return ResourceManager.GetString("SaldoDeFerias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o sobrenome do colaborador..
        /// </summary>
        public static string SobrenomeColaborador {
            get {
                return ResourceManager.GetString("SobrenomeColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve conter entre 2 e 100 caracteres..
        /// </summary>
        public static string TamanhoNomeColaborador {
            get {
                return ResourceManager.GetString("TamanhoNomeColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome deve conter entre 1 e 100 caracteres..
        /// </summary>
        public static string TamanhoSobrenomeColaborador {
            get {
                return ResourceManager.GetString("TamanhoSobrenomeColaborador", resourceCulture);
            }
        }
    }
}
