// <auto-generated />
using System;
using RH.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RH.Infra.Data.Migrations
{
    [DbContext(typeof(CodeiziContext))]
    [Migration("20200731221504_OcorrenciaDeFerias")]
    partial class OcorrenciaDeFerias
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RH.Domain.Colaboradores.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnName("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacaoContratual")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("RH.Domain.Colaboradores.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnName("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnName("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoAquisitivo")
                        .HasColumnType("datetime2");

                    b.Property<double>("SalarioContratual")
                        .HasColumnName("SalarioContratual")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("RH.Domain.Ocorrencias.Ferias.OcorrenciaDeFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContradoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnName("DataDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DiasDeAbono")
                        .HasColumnName("DiasDeAboino")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DiasDeFerias")
                        .HasColumnName("DiasDeFerias")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("PeriodoArquisitivo")
                        .HasColumnName("PeriodoAquisitivo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContradoId");

                    b.ToTable("OcorrenciaDeFerias");
                });

            modelBuilder.Entity("RH.Domain.Colaboradores.Colaborador", b =>
                {
                    b.OwnsOne("RH.Domain.SharedKernel.ValueObjects.NomePessoa", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ColaboradorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnName("Nome")
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnName("Sobrenome")
                                .HasColumnType("nvarchar(100)")
                                .HasMaxLength(100);

                            b1.HasKey("ColaboradorId");

                            b1.ToTable("Colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorId");
                        });
                });

            modelBuilder.Entity("RH.Domain.Colaboradores.Contrato", b =>
                {
                    b.HasOne("RH.Domain.Colaboradores.Colaborador", "Colaborador")
                        .WithMany("Contratos")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RH.Domain.Ocorrencias.Ferias.OcorrenciaDeFerias", b =>
                {
                    b.HasOne("RH.Domain.Colaboradores.Contrato", "Contrato")
                        .WithMany("Ferias")
                        .HasForeignKey("ContradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
